datasets:
  dataset_name: 'mvtec_ad'  # choice ['mvtec_ad', 'visa']
  data_path: ./data/mvtec_anomaly_detection/
  class_name: 'ALL'
  img_resize: 518
  divide_num: 1
models:
  backbone_name: 'ViT-L-14-336'
  pretrained: 'openai'
  batch_size: 1
  feature_layers: [5, 11, 17, 23]
  r_list: [1, 3, 5]
device: 0
testing:
  output_dir: 'output'
  vis: True
  vis_type: single_norm # choice ['single_norm', 'whole_norm']
  save_excel: True


# models['backbone_name'] choice:
# ViT-B-32 | ViT-B-16 | ViT-B-16-plus-240
# ViT-L-14 | ViT-L-14-336
# dino_vitbase8 | dino_vitbase16
# dinov2_vitb14 | dinov2_vitl14
# resnet18 | resnet34 | resnet50 | resnet101
# wideresnet50 | wideresnet101

# models['pretrained'] choice:
# openai (apply to ViT-B-32, ViT-B-16, ViT-L-14 and ViT-L-14-336)
# laion400m_e31 (apply to ViT-B-32, ViT-B-16, ViT-B-16-plus-240 and ViT-L-14)
# laion400m_e32 (apply to ViT-B-32, ViT-B-16, ViT-B-16-plus-240 and ViT-L-14)
